package net.darkhax.bladecraft;

import java.util.Arrays;

import net.darkhax.bladecraft.lib.Reference;
import net.darkhax.bladecraft.proxy.ClientProxy;
import net.darkhax.bladecraft.proxy.CommonProxy;
import net.minecraft.command.ICommandManager;
import net.minecraft.command.ServerCommandManager;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class BladeCraft {

	@SidedProxy(serverSide = Reference.PROXY_SERVER, clientSide = Reference.PROXY_CLIENT)
	public static CommonProxy proxy;

	@Mod.Instance(Reference.MOD_ID)
	public static BladeCraft instance;
	 
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {

		ClientProxy.registerItemRenders();
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {

	}

	private void getModMeta(ModMetadata meta) {

		meta.authorList = Arrays.asList(new String[] { "Darkhax" });
		meta.logoFile = "null";
		meta.autogenerated = false;
		meta.credits = "Coded by Darkhax and Ghostrec35. Ideas by Thisguy1045";
		meta.description = "Bladecraft allows for extensive custimation options for your Minecraft Weapons!";
		meta.url = "www.darkhax.net";
	}
}