package net.epoxide.bladecraft;

import java.util.Arrays;

import net.epoxide.bladecraft.block.BCBlocks;
import net.epoxide.bladecraft.command.CommandDye;
import net.epoxide.bladecraft.event.ToolTipEventHandler;
import net.epoxide.bladecraft.handler.ConfigurationHandler;
import net.epoxide.bladecraft.item.BCItems;
import net.epoxide.bladecraft.item.crafting.DyeableItems;
import net.epoxide.bladecraft.item.crafting.RGBEntry;
import net.epoxide.bladecraft.network.NetworkManager;
import net.epoxide.bladecraft.proxy.ProxyCommon;
import net.epoxide.bladecraft.util.Reference;
import net.minecraft.client.Minecraft;
import net.minecraft.command.ServerCommandManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.world.IWorldAccess;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION, guiFactory = Reference.FACTORY)
public class Bladecraft {

    @SidedProxy(serverSide = Reference.PROXY_COMMON, clientSide = Reference.PROXY_CLIENT)
    public static ProxyCommon proxy;

    @Mod.Instance(Reference.MOD_ID)
    private static Bladecraft instance;
        
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) 
    {
        setModMeta(event.getModMetadata());
        ConfigurationHandler.initialize(event.getSuggestedConfigurationFile());
        BCBlocks.initialize();
        BCItems.initialize();
        NetworkManager.initialize();
        
        TileEntity.addMapping(net.epoxide.bladecraft.tileentity.TileEntityForge.class, "BladeCraftForge");
        TileEntity.addMapping(net.epoxide.bladecraft.tileentity.TileEntityMixer.class, "BladeCraftMixer");
         
        MinecraftForge.EVENT_BUS.register(new ToolTipEventHandler());
        NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
    }
    
    @EventHandler
    public void onPostInit(FMLPostInitializationEvent event)
    {        
        proxy.registerSidedEvents();
        proxy.registerBlockItemRenderers();
        RGBEntry entry = DyeableItems.getDyeComponentValue(new ItemStack(Items.dye, 1, 0));   
    }
    
    @EventHandler
    public void onServerStarting(FMLServerStartingEvent event) 
    {
        ServerCommandManager manager = (ServerCommandManager) event.getServer().getCommandManager();
        manager.registerCommand(new CommandDye());
    }

    private void setModMeta(ModMetadata meta) 
    {
        meta.name = "Bladecraft";
        meta.modId = Reference.MOD_ID;
        meta.version = Reference.VERSION;
        meta.authorList = Arrays.asList("Ghostrec35", "Darkhax", "Thisguy1045");
        meta.autogenerated = false;
        meta.description = "A mod that provides the ability to color swords.";
        meta.logoFile = "";
        meta.url = "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288864-1-5-2-forge-bladecraft-ssp-smp-lan";
    }
    
    public static Bladecraft instance()
    {
    	return instance;
    }
}