package net.epoxide.bladecraft;

import java.util.Arrays;

import net.epoxide.bladecraft.command.CommandDye;
import net.epoxide.bladecraft.handler.ConfigurationHandler;
import net.epoxide.bladecraft.item.crafting.DyeableItems;
import net.epoxide.bladecraft.proxy.ProxyCommon;
import net.epoxide.bladecraft.util.Reference;
import net.minecraft.command.ServerCommandManager;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION, guiFactory = Reference.FACTORY)
public class Bladecraft {

    @SidedProxy(serverSide = Reference.PROXY_COMMON, clientSide = Reference.PROXY_CLIENT)
    public static ProxyCommon proxy;

    @Mod.Instance(Reference.MOD_ID)
    public static Bladecraft instance;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {

        setModMeta(event.getModMetadata());
        new ConfigurationHandler(event.getSuggestedConfigurationFile());
        proxy.registerSidededEvents();
        
        System.out.println(DyeableItems.calculateEntryFromColorValue(1));
    }
    
    @EventHandler
    public void onServerStarting(FMLServerStartingEvent event) {

        ServerCommandManager manager = (ServerCommandManager) event.getServer().getCommandManager();
        manager.registerCommand(new CommandDye());
    }


    private void setModMeta(ModMetadata meta) {

        // TODO add more details
        meta.description = "Bladecraft";
        meta.authorList = Arrays.asList("Ghostrec35", "Darkhax", "Thisguy1045");
        meta.autogenerated = false;
    }
}